version: '3.1'

services:

  vote:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
