// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: proto/voting.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CryptoCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Upvote   int64  `protobuf:"varint,2,opt,name=upvote,proto3" json:"upvote,omitempty"`
	Downvote int64  `protobuf:"varint,3,opt,name=downvote,proto3" json:"downvote,omitempty"`
}

func (x *CryptoCreateReq) Reset() {
	*x = CryptoCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoCreateReq) ProtoMessage() {}

func (x *CryptoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoCreateReq.ProtoReflect.Descriptor instead.
func (*CryptoCreateReq) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CryptoCreateReq) GetUpvote() int64 {
	if x != nil {
		return x.Upvote
	}
	return 0
}

func (x *CryptoCreateReq) GetDownvote() int64 {
	if x != nil {
		return x.Downvote
	}
	return 0
}

type CreateCryptoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateCryptoRes) Reset() {
	*x = CreateCryptoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCryptoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCryptoRes) ProtoMessage() {}

func (x *CreateCryptoRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCryptoRes.ProtoReflect.Descriptor instead.
func (*CreateCryptoRes) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCryptoRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCryptoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCryptoReq) Reset() {
	*x = GetCryptoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCryptoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoReq) ProtoMessage() {}

func (x *GetCryptoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoReq.ProtoReflect.Descriptor instead.
func (*GetCryptoReq) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{2}
}

func (x *GetCryptoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Crypto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Upvote   int64  `protobuf:"varint,3,opt,name=upvote,proto3" json:"upvote,omitempty"`
	Downvote int64  `protobuf:"varint,4,opt,name=downvote,proto3" json:"downvote,omitempty"`
}

func (x *Crypto) Reset() {
	*x = Crypto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Crypto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crypto) ProtoMessage() {}

func (x *Crypto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crypto.ProtoReflect.Descriptor instead.
func (*Crypto) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{3}
}

func (x *Crypto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Crypto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Crypto) GetUpvote() int64 {
	if x != nil {
		return x.Upvote
	}
	return 0
}

func (x *Crypto) GetDownvote() int64 {
	if x != nil {
		return x.Downvote
	}
	return 0
}

type UpvoteCryptoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpvoteCryptoReq) Reset() {
	*x = UpvoteCryptoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpvoteCryptoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpvoteCryptoReq) ProtoMessage() {}

func (x *UpvoteCryptoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpvoteCryptoReq.ProtoReflect.Descriptor instead.
func (*UpvoteCryptoReq) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{4}
}

func (x *UpvoteCryptoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpvoteCryptoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpvoteCryptoRes) Reset() {
	*x = UpvoteCryptoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpvoteCryptoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpvoteCryptoRes) ProtoMessage() {}

func (x *UpvoteCryptoRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpvoteCryptoRes.ProtoReflect.Descriptor instead.
func (*UpvoteCryptoRes) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{5}
}

func (x *UpvoteCryptoRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DownvoteCryptoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DownvoteCryptoReq) Reset() {
	*x = DownvoteCryptoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownvoteCryptoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownvoteCryptoReq) ProtoMessage() {}

func (x *DownvoteCryptoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownvoteCryptoReq.ProtoReflect.Descriptor instead.
func (*DownvoteCryptoReq) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{6}
}

func (x *DownvoteCryptoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownvoteCryptoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DownvoteCryptoRes) Reset() {
	*x = DownvoteCryptoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownvoteCryptoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownvoteCryptoRes) ProtoMessage() {}

func (x *DownvoteCryptoRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownvoteCryptoRes.ProtoReflect.Descriptor instead.
func (*DownvoteCryptoRes) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{7}
}

func (x *DownvoteCryptoRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteCryptoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCryptoReq) Reset() {
	*x = DeleteCryptoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCryptoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCryptoReq) ProtoMessage() {}

func (x *DeleteCryptoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCryptoReq.ProtoReflect.Descriptor instead.
func (*DeleteCryptoReq) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCryptoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCryptoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteCryptoRes) Reset() {
	*x = DeleteCryptoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCryptoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCryptoRes) ProtoMessage() {}

func (x *DeleteCryptoRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCryptoRes.ProtoReflect.Descriptor instead.
func (*DeleteCryptoRes) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCryptoRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCryptosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCryptosReq) Reset() {
	*x = ListCryptosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCryptosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCryptosReq) ProtoMessage() {}

func (x *ListCryptosReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCryptosReq.ProtoReflect.Descriptor instead.
func (*ListCryptosReq) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{10}
}

type ListCryptosRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crypto []*Crypto `protobuf:"bytes,1,rep,name=crypto,proto3" json:"crypto,omitempty"`
}

func (x *ListCryptosRes) Reset() {
	*x = ListCryptosRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_voting_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCryptosRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCryptosRes) ProtoMessage() {}

func (x *ListCryptosRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voting_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCryptosRes.ProtoReflect.Descriptor instead.
func (*ListCryptosRes) Descriptor() ([]byte, []int) {
	return file_proto_voting_proto_rawDescGZIP(), []int{11}
}

func (x *ListCryptosRes) GetCrypto() []*Crypto {
	if x != nil {
		return x.Crypto
	}
	return nil
}

var File_proto_voting_proto protoreflect.FileDescriptor

var file_proto_voting_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0f, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x70, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x70, 0x76,
	0x6f, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x22,
	0x21, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52,
	0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x60, 0x0a, 0x06, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e,
	0x76, 0x6f, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e,
	0x76, 0x6f, 0x74, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x43, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x55, 0x70, 0x76, 0x6f, 0x74,
	0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65,
	0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x44, 0x6f, 0x77,
	0x6e, 0x76, 0x6f, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x22, 0x31, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x06,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x06, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x32, 0xbd, 0x02,
	0x0a, 0x0d, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x32, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12,
	0x10, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x10, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x12, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x07, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x32, 0x0a, 0x0c, 0x55, 0x70, 0x76, 0x6f,
	0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x10, 0x2e, 0x55, 0x70, 0x76, 0x6f, 0x74,
	0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x55, 0x70, 0x76,
	0x6f, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0e,
	0x44, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x12,
	0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x43, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x10, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x12, 0x0f, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x30, 0x01, 0x42, 0x05, 0x5a,
	0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_voting_proto_rawDescOnce sync.Once
	file_proto_voting_proto_rawDescData = file_proto_voting_proto_rawDesc
)

func file_proto_voting_proto_rawDescGZIP() []byte {
	file_proto_voting_proto_rawDescOnce.Do(func() {
		file_proto_voting_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_voting_proto_rawDescData)
	})
	return file_proto_voting_proto_rawDescData
}

var file_proto_voting_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_voting_proto_goTypes = []interface{}{
	(*CryptoCreateReq)(nil),   // 0: CryptoCreateReq
	(*CreateCryptoRes)(nil),   // 1: CreateCryptoRes
	(*GetCryptoReq)(nil),      // 2: GetCryptoReq
	(*Crypto)(nil),            // 3: Crypto
	(*UpvoteCryptoReq)(nil),   // 4: UpvoteCryptoReq
	(*UpvoteCryptoRes)(nil),   // 5: UpvoteCryptoRes
	(*DownvoteCryptoReq)(nil), // 6: DownvoteCryptoReq
	(*DownvoteCryptoRes)(nil), // 7: DownvoteCryptoRes
	(*DeleteCryptoReq)(nil),   // 8: DeleteCryptoReq
	(*DeleteCryptoRes)(nil),   // 9: DeleteCryptoRes
	(*ListCryptosReq)(nil),    // 10: ListCryptosReq
	(*ListCryptosRes)(nil),    // 11: ListCryptosRes
}
var file_proto_voting_proto_depIdxs = []int32{
	3,  // 0: ListCryptosRes.crypto:type_name -> Crypto
	0,  // 1: VotingService.CreateCrypto:input_type -> CryptoCreateReq
	2,  // 2: VotingService.GetCrypto:input_type -> GetCryptoReq
	4,  // 3: VotingService.UpvoteCrypto:input_type -> UpvoteCryptoReq
	6,  // 4: VotingService.DownvoteCrypto:input_type -> DownvoteCryptoReq
	8,  // 5: VotingService.DeleteCrypto:input_type -> DeleteCryptoReq
	10, // 6: VotingService.ListCryptos:input_type -> ListCryptosReq
	1,  // 7: VotingService.CreateCrypto:output_type -> CreateCryptoRes
	3,  // 8: VotingService.GetCrypto:output_type -> Crypto
	5,  // 9: VotingService.UpvoteCrypto:output_type -> UpvoteCryptoRes
	7,  // 10: VotingService.DownvoteCrypto:output_type -> DownvoteCryptoRes
	9,  // 11: VotingService.DeleteCrypto:output_type -> DeleteCryptoRes
	11, // 12: VotingService.ListCryptos:output_type -> ListCryptosRes
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_voting_proto_init() }
func file_proto_voting_proto_init() {
	if File_proto_voting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_voting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CryptoCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCryptoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCryptoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Crypto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpvoteCryptoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpvoteCryptoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownvoteCryptoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownvoteCryptoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCryptoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCryptoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCryptosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_voting_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCryptosRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_voting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_voting_proto_goTypes,
		DependencyIndexes: file_proto_voting_proto_depIdxs,
		MessageInfos:      file_proto_voting_proto_msgTypes,
	}.Build()
	File_proto_voting_proto = out.File
	file_proto_voting_proto_rawDesc = nil
	file_proto_voting_proto_goTypes = nil
	file_proto_voting_proto_depIdxs = nil
}
